export const tailwindColors = [
  { name: "schwarz", value: "black", class: "bg-black" },
  { name: "weiß", value: "white", class: "bg-white" },
  { name: "grau", value: "gray", class: "bg-gray-600" },
  { name: "rot", value: "red", class: "bg-red-600" },
  { name: "gelb", value: "yellow", class: "bg-yellow-600" },
  { name: "grün", value: "green", class: "bg-green-600" },
  { name: "blau", value: "blue", class: "bg-blue-600" },
  { name: "indigo", value: "indigo", class: "bg-indigo-600" },
  { name: "violett", value: "violet", class: "bg-violet-600" },
  { name: "rosa", value: "pink", class: "bg-pink-600" },
  { name: "limette", value: "lime", class: "bg-lime-600" },
  { name: "bernstein", value: "amber", class: "bg-amber-600" },
  { name: "orange", value: "orange", class: "bg-orange-600" },
  { name: "grün-blau", value: "teal", class: "bg-teal-600" },
  { name: "zyan", value: "cyan", class: "bg-cyan-600" },
  { name: "himbeerrot", value: "rose", class: "bg-rose-600" },
  { name: "schiefergrau", value: "slate", class: "bg-slate-600" },
  { name: "zink", value: "zinc", class: "bg-zinc-600" },
  { name: "neutral", value: "neutral", class: "bg-neutral-600" },
  { name: "stein", value: "stone", class: "bg-stone-600" },
  { name: "fuchsia", value: "fuchsia", class: "bg-fuchsia-600" },
  { name: "lila", value: "purple", class: "bg-purple-600" },
  { name: "smaragd", value: "emerald", class: "bg-emerald-600" },
  { name: "himmelblau", value: "sky", class: "bg-sky-600" },
];
